markreplace = {
"markreplace":{
	" Alarm": " [b]Alarm[/b]", " Bond": " [b]Bond[/b]", " BOND": " [b]Bond[/b]",
	" ENCORE": " [b]Encore[/b]", " Encore": " [b]Encore[/b]", " Assit": " [b]Assist[/b]", " ASSIST": " [b]Assist[/b]",
	" Backup": " [b]Backup[/b]", " BACKUP": " [b]Backup[/b]", " Brainstorm": " [b]Brainstorm[/b]",
	" BRAINSTORM": " [b]Brainstorm[/b]", " Change": " [b]Change[/b]", " CHANGE": " [b]Change[/b]", " Accelerate": " [b]Accelerate[/b]", " ACCELERATE": " [b]Accelerate[/b]",
	" Memory": " [b]Memory[/b]", " MEMORY": " [b]Memory[/b]"," RECOLLECTION":" [b]Memory[/b]"," Bodyguard": " [b]Great Performance[/b]",
	" Experience": " [b]Experience[/b]"," EXPERIENCE": " [b]Experience[/b]","if \"": "if a card named \"","Level-Up":"level up",
	"this gain": "this card get", "All your": "All of your", "in front of this gain": "in front of this card get",
	"this is placed from your hand to the Stage": "this card is placed on stage from your hand",
	"pay cost": "pay the cost", "is in the Climax Zone": "is in your climax area", "If so": "If you do",
	"If it's not a": "If the revealed card is not a", "When this attacks": "When this card attacks",
	"Otherwise put the card back where it was)": "If it is, return the revealed card to its original place.)",
	"choose a Character in your Waiting Room and return it to your hand": "choose a character from your waiting room, and return it to your hand",
	"reveal them,": "reveal them to your opponent", "for the turn":"until end of turn",
	"put them in your hand": "put them into your hand",
	"huffle your Library": "huffle your deck afterwards", "in your Stock": "in to your stock",
	"When this is placed from hand to the Climax Zone": "When this card is placed on your climax area from hand",
	"Discard this card from your hand to the Waiting Room": "Put this card from your hand into your waiting room",
	"Stage": "stage", "Library": "deck", "library": "deck","Libraries":"decks","libraries":"decks" ,"gain": "get",
	"Character":"character","Waiting Room":"waiting room","Opp":"opp","your Memory":"your memory","to Memory":"to memory","Power":"power","Soul":"soul",
	"Front Row Slots on Stage":"position on your center stage","Front Row":"center stage","Level":"level","; character":"; Character", "front row":"center stage",
	"CONT character":"CONT Character",
	"(1)": "①", "(2)": "②", "(3)": "③", "(4)": "④", "(5)": "⑤","(6)": "⑥"},
"square" : {"[REST]": "IREST", "[STAND]": "ISTAND", "[REVERSE]": "IREVERSE","[Rest": "[IREST","Rested":"IREST"," Rest": "IREST"," Standing": "ISTAND",
         "[COUNTER]": "ICOUNTER","Reversed":"IREVERSE","Reverse":"IREVERSE","Stand":"ISTAND","[SOUL]":"ISOUL",
          "[AUTO]": "AUTO", "[ACT]": "ACT", "[CONT]": "CONT", "[DOOR]": "IDOOR", "[STANDBY]": "ISTANDBY",
          "[DRAW]": "IDRAW", "[STOCK]": "ISTOCK", "[TREASURE]": "ITREASURE", "[GATE]": "IGATE", "[BOUNCE]": "IBOUNCE",
          "[SHOT]": "ISHOT", "[CHOICE]": "ICHOICE","[Counter]":"ICOUNTER","[ALARM]":"IALARM"," CX COMBO": "ICXCOMBO","[CXCOMBO]": "ICXCOMBO","【ＣＸコンボ】":"IJCXCOMBO",
          "【永】": "IJCONT", "【起】": "IJACT", "【自】": "IJAUTO", "【リターン】": "IBOUNCE", "【ショット】": "ISHOT", "【チョイス】": "ICHOICE",
          "【トレジャー】": "ITREASURE", "【プール】": "ISTOCK", "【カムバック】": "IDOOR", "【ドロー】": "IDRAW","【ソウル】":"ISOUL",
          "【ゲート】": "IGATE","【カウンター】": "ICOUNTER","【リバース】": "IREVERSE","【レスト】": "IREST","【スタンド】":"ISTAND","【スタンバイ】": "ISTANDBY"
          },
"anchors" : {"ISTANDBY": 1,"IREST": 1, "ISTAND": 1, "IREVERSE": 1, "IJAUTO": 1, "IJACT": 1, "IJCONT": 1,"AUTO": 2, "ACT": 2, "CONT": 2, "IDOOR": 1, "IDRAW": 1,
           "ISTOCK": 1, "ITREASURE": 2, "IGATE": 1, "IBOUNCE": 1, "ISHOT": 2, "ICHOICE": 2,"IALARM":1,"ICOUNTER":1,"ICXCOMBO":3,"IJCXCOMBO":3,"ISOUL":1},
"set_only" : {"(Macross Frontier Only)":"Macross Frontier","(Kud Wafter Only)":"Kud Wafter"}
}
